{
	"version": 1636448310,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/ตึกpng-sheet0.png",
		"images/images-sheet0.png",
		"images/ดาวน์โหลด-sheet0.png",
		"images/662873_pngfilesizesniperpng-sheet0.png",
		"images/images2-sheet0.png",
		"images/pngwingcom-sheet0.png",
		"images/palaceroomroyalemptyinteriorempirestyle_-sheet0.png",
		"images/รูปภาพ-sheet0.png",
		"images/รูปภาพ2-sheet0.png",
		"images/sprite-sheet0.png",
		"images/bull-sheet0.png",
		"images/ppppp-sheet0.png",
		"media/gunsnglshotfireex-pe1107203.ogg",
		"media/mouse-click-00-m-fesliyanstudios.com2.ogg",
		"media/strategy (dramatic music) - vanoss gaming background music (hd).ogg",
		"media/bullet-hitting-ground-sound-effect-_1_.ogg",
		"media/applause-sound-effect2.ogg",
		"media/fail-sound-effect.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}